`language: go

go:
  - tip

git:
  depth: 1

install:
  - export GOPATH="$HOME/gopath"
  - go get -v -t -d github.com/omines/eurodnsgo/...

script:
  - go test -v -cover github.com/omines/eurodnsgo/...

after_success:
  - bash <(curl -s https://codecov.io/bash)